services:
  scraperr:
    image: jpyles0524/scraperr:latest
    container_name: scraperr
    command: ["npm", "run", "start"]
    environment:
      - 'NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}' # your API URL
      - 'SERVER_URL=${SERVER_URL}' # your docker container API URL
    ports:
      - '${scraperr_port}'
    networks:
      - web
    labels:
      - "traefik.enable=true" # Эта метка уже должна быть, если Traefik включен для сервиса
      - "traefik.http.services.scraperr.loadbalancer.server.port=3000" # <-- ВАЖНАЯ МЕТКА!
  scraperr_api:
    init: True
    image: jpyles0524/scraperr_api:latest
    environment:
      - LOG_LEVEL=INFO
    container_name: scraperr_api
    ports:
      - '${scraperr_api_port}'
    volumes:
      - "$PWD/data:/project/app/data"
      - "$PWD/media:/project/app/media"
    networks:
      - web

networks:
  web:
